version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 080231293217.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Listing current directory contents...
      - ls -la
      - echo Showing Dockerfile...
      - cat Dockerfile
      - echo Building Docker image...
      - docker build -t static-website .
      - docker tag static-website:latest 080231293217.dkr.ecr.us-east-1.amazonaws.com/static-website:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 080231293217.dkr.ecr.us-east-1.amazonaws.com/static-website

artifacts:
  files:
    - '**/*'
