version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.$AWS_REGION.amazonaws.com)

  build:
    commands:
      - echo Build started on `date`
      - docker build -t static-website .
      - docker tag static-website:latest <your-ecr-repo-url>:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push <your-ecr-repo-url>:latest

artifacts:
  files:
    - '**/*'
